"""Add extracted text to resumes

Revision ID: 35d655612b8a
Revises: 2e67741e19c7
Create Date: 2026-08-08 20:55:24.325496

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35d655612b8a'
down_revision: Union[str, Sequence[str], None] = '2e67741e19c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resumes', sa.Column('extracted_text', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resumes', 'extracted_text')
    # ### end Alembic commands ###
